services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=runnerz'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'
